### ISSUE TITLE
fix: ReviewOutcomeObserver + QhorusPrReviewService compilation failures from foundation snapshot evolution

### ISSUE THREAD

**Issue by mdproctor** [casehubio/devtown#76]
## Problem

Two files in `app/` don't compile against the latest foundation snapshots:

1. `ReviewOutcomeObserver.java` — cannot find symbol (likely a renamed/removed class in casehub-engine)
2. `QhorusPrReviewService.java` — no suitable method for `create()` (ChannelService API changed in casehub-qhorus)

## Context

Pre-existing breakage surfaced during devtown#5 implementation. The foundation snapshot cascade (ledger#131, engine#460, qhorus#269) fixed the tenancyId/field-shadowing issues but also evolved other APIs that these two files depend on.

The devtown#5 feature code (IncidentFeedbackService, IncidentFeedbackResource, domain types) compiles and all 15 tests pass independently. These two files are unrelated to the incident feedback feature.

## Impact

Full `mvn install` fails. Domain and review modules pass (55 tests). App module compilation blocked by these two files.
